version: '3.9'
services:
  database:
    image: mysql
    container_name: database-ddd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: training
    volumes:
      - /data:/var/lib/mysql
    networks:
      - database
    ports:
      - "3306:3306"
  api:
    container_name: service-ddd
    build:
      dockerfile: docker/go/Dockerfile
    environment:
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      DB_PASS: "${DB_PASS}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped
    links:
      - database
    networks:
      - database
networks:
  database:
    name: database_network
    driver: bridge
volumes:
  db:
    external: false
